apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-mysql #mysql-deployment
  labels:
    app: wordpress
#  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
    strategy: #add
      type: Recreate #add
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - name: mysql #mysql-container
        image: mysql:5.7 #mysql
        env:
        - name: MYSQL_DATABASE
#          value: wordpress
          valueFrom:
            secretKeyRef:
              name: app-wordpress-secret
              key: mysql-database-name
        - name: MYSQL_USER
          #value: toto
          valueFrom:
            secretKeyRef:
              name: app-wordpress-secret
              key: mysql-root-username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-wordpress-secret #mysqldb-secret
              key: mysql_password #mysql-root-password
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-wordpress-secret #mysqldb-secret
              key: mysql_random_root_password #mysql-random-root-password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage #mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage #mysql-storage
        hostPath: 
          path: /data/mysql


