apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
    strategy:
      type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - name: wordpress #wordpress-container
        image: wordpress:latest #wordpress  
        ports:
        - containerPort: 80
          name: wordpress #add
        env:
        - name: WORDPRESS_DB_HOST
          value: wp-mysql #mysql-deployment
        - name: WORDPRESS_DB_NAME
          value: wordpress
#          valueFrom:
#            secretKeyRef:
#              name: mysqldb-secret
#              key: mysql-database-name
        - name: WORDPRESS_DB_USER
          value: toto
#          valueFrom:
#            secretKeyRef:
#              name: mysqldb-secret
#              key: mysql-root-username
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-wordpress-secret #mysqldb-secret
              key: wordpress_db_password #mysql-root-password
        volumeMounts:
        - name: wp-persitent-storage #wordpress-storage
          mountPath: /var/www/html
      volumes:
      - name: wp-persitent-storage #wordpress-storage
        hostPath: 
          path: /data/wordpress
