apiVersion: v1
kind: Service
metadata:
  name: mysqldb-service
  labels:
    name: wordpress
spec:
  selector:
    app: wordpress
    tier: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306