apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - name: wordpress-container
        image: wordpress
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-deployment
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysqldb-secret
              key: mysql-database-name
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: mysqldb-secret
              key: mysql-root-username
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqldb-secret
              key: mysql-root-password
        volumeMounts:
        - name: wordpress-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-storage
        hostPath: 
          path: /data/wordpress
